### ISSUE TITLE
女优别名错误：若宮はずき > 宝生リリー

### ISSUE THREAD

**Issue by xjasonlyu** [gfriends/gfriends#108]
发现 https://github.com/gfriends/gfriends/commit/42314ed57d80df5261d4c84a22777bce845f1b1e Filetree里`若宮はずき`会被当成`宝生リリー`

如：`"若宮はずき.jpg":"AI-Fix-宝生リリー.jpg?t=1607433670"`

**Comment by xinxin8816** [comment]
OK 下次刷新文件树会修复

**Comment by xjasonlyu** [comment]
已修复，更新后端即可。

**Comment by xinxin8816** [comment]
已修复此别名错误
