### ISSUE TITLE
v-Attackers/浜崎真緒.jpg 不是头像图片

### ISSUE THREAD

**Issue by frosty5689** [gfriends/gfriends#115]
Plex用JAVnfoMovieImporter自动匹配到了这个studio的头像。然后看起来就是一个“Now Printing”。 能否删除还是会被bot自动生成？

https://github.com/gfriends/gfriends/blob/master/Content/v-Attackers/%E6%B5%9C%E5%B4%8E%E7%9C%9F%E7%B7%92.jpg
https://github.com/gfriends/gfriends/blob/master/Content/v-Attackers/AI-Fix-%E6%B5%9C%E5%B4%8E%E7%9C%9F%E7%B7%92.jpg

**Comment by xinxin8816** [comment]
感谢提醒，已删除
