### ISSUE TITLE
羅馬拼音的女友, 無法配匹

### ISSUE THREAD

**Issue by nova168168** [gfriends/gfriends#79]
我直接在 windows 上運行 "Gfriends Inputer" , 出現羅馬拼音的女友, 無法配匹 , 是甚麼原因? 要怎樣配置呢? 

未找到：Abe Mikako
未找到：Abeno Miku
未找到：Afuro Takahashi
未找到：Agatsuma Riho
未找到：Aiga Mizuki
未找到：Aihara Yui
未找到：Aika Mirei
未找到：Aine Maria
未找到：Aisaka Chika
未找到：Aise Miki
未找到：Aise Ruka
未找到：Aizawa Minami
未找到：Aizawa Rin
未找到：Aizome Tomohisa
未找到：Akai Suisei
未找到：Akane Maiko
未找到：Akari Tsumugi
未找到：Akemi Kou
未找到：Akemi Miu

**Comment by xinxin8816** [comment]
别名数据库中罗马拼音的收录还不完整

如果您有相关数据库可以提供给我

**Comment by nova168168** [comment]
用如下網址搜括一下可以嗎?

http://www.playno1.com/forum.php?mod=forumdisplay&fid=79&page=1&filter=sortid&sortid=2


[image: image.png]

**Comment by xinxin8816** [comment]
如果有更全面的站点就更好了，这个站点只有不到900位

**Comment by nova168168** [comment]
哈哈, 基本上應該夠用了吧, 沒的再補!

在 2022年1月28日週五 19:07，Zealer Chan ***@***.***> 寫道：

> 如果有更全面的站点就更好了，这个站点只有不到900位
>
> 用如下網址搜括一下可以嗎?
> http://www.playno1.com/forum.php?mod=forumdisplay&fid=79&page=1&filter=sortid&sortid=2
> [image: image.png]
> … <#m_5496356333791683811_>

**Comment by xinxin8816** [comment]
我找到了个更好的源，抽空搞定

**Comment by nova168168** [comment]
侬结棍 , 期待中

**Comment by xinxin8816** [comment]
```
未找到：Abe Mikako
未找到：Abeno Miku
未找到：Afuro Takahashi
未找到：Agatsuma Riho
未找到：Aiga Mizuki
未找到：Aihara Yui
未找到：Aika Mirei
未找到：Aine Maria
未找到：Aisaka Chika
未找到：Aise Miki
未找到：Aise Ruka
未找到：Aizawa Minami
未找到：Aizawa Rin
未找到：Aizome Tomohisa
未找到：Akai Suisei
未找到：Akane Maiko
未找到：Akari Tsumugi
未找到：Akemi Kou
未找到：Akemi Miu
```
你这个是从用什么插件/软件刮削的演员名？
`Abe Mikako` 怎么先姓后名，一般都是叫 `Mikako Abe` 吧

**Comment by nova168168** [comment]
Javinizer  , 剛開始不太會用, 不停換日文, 英文的, 都是程序自己搜刮的! 不知道是不是它的問題!

**Comment by xinxin8816** [comment]
对这种情况做了适配，现在应该好了

**Comment by nova168168** [comment]
剛剛試了一下,

√ 导入完成 成

Emby / Jellyfin 演职人员共 816 人，其中 32 人之前已有头像
本次导入 273 人，还有 512 人没有头像

還有512沒有, 哈哈

未找到：Afuro Takahashi
未找到：Aisaka Chika
未找到：Aise Ruka
未找到：Aizawa Rin
未找到：Aizome Tomohisa
未找到：Akai Suisei
未找到：Akane Maiko
未找到：Akemi Kou
未找到：Aki Hideto
未找到：Akinori
未找到：Akira Oniisan
未找到：Alice Kisaki
未找到：Amagami Misa
未找到：Amamiya Mona
未找到：Amane Kanon
未找到：Amano Koyuki
未找到：Amazawa Yukine
未找到：Ani- Nakamura
未找到：Anna
未找到：Aohige Daigo
未找到：Aoi Tsubasa
未找到：Aosora Konatsu
未找到：Aoyama Hana
未找到：Arakaki Kotori
未找到：Araki Fumika
未找到：Araki Mai
未找到：Arashiyama Michiru
未找到：Arimura Erika
未找到：Arisu Kusunoki
未找到：Asagiri Jou
未找到：Asahina Akari
未找到：Asahina Nanase

**Comment by xinxin8816** [comment]
查了一下 `Afuro Takahashi` 是正经电影男演员，还有 `Arashiyama Michiru` 这种电影导演等后勤人员不在收录范围
仓库**只收录日本女友**，如果你的媒体服务器是正经电影和小电影混用的话，许多人没有头像是正常现象
