### ISSUE TITLE
plex服务器的JAVnfoMoviesImporter插件好像停止更新了，头像还是很久以前的，部分还显示不了

### ISSUE THREAD

**Issue by heptagonlin** [gfriends/gfriends#82]
plex服务器的JAVnfoMoviesImporter插件好像停止更新很久了，头像还是很久以前的，部分还显示不了，能继续维护更新JAVnfoMoviesImporter这个插件吗？

**Comment by xinxin8816** [comment]
JAVnfoMoviesImporter 头像调用本仓库，目前还可以使用。维护相关问题请咨询其作者。

**Comment by heptagonlin** [comment]
但是作者已经停更了，有大大接手一下吗，可怜一下我们这样plex用户

**Comment by ddd354** [comment]
确实现在的版本是可以用的
不过由于Filetree.json大小的增长有的时候(大部分时候) 下载这个文件会失败 就会导致信息写入不成功

**Comment by heptagonlin** [comment]
ddd354，大大你好，你有时间的话。可以继续开发这个软件吗？？ 我以为你离开不来Github了。

**Comment by kudouxinyi** [comment]
求更新~

**Comment by kudouxinyi** [comment]
我手动把头像文件都下载下来了，请问应该存到哪个文件夹可以被调用？

**Comment by xmcdlf1992** [comment]
您试出来了吗？我尝试了很多次都无法读取到头像信息

**Comment by xmcdlf1992** [comment]
> 确实现在的版本是可以用的 不过由于Filetree.json大小的增长有的时候(大部分时候) 下载这个文件会失败 就会导致信息写入不成功

没有用呀

**Comment by tmrsm** [comment]
> plex服务器的JAVnfoMoviesImporter插件好像停止更新很久了，头像还是很久以前的，部分还显示不了，能继续维护更新JAVnfoMoviesImporter这个插件吗？

https://github.com/ddd354/JAVnfoMoviesImporter.bundle/issues/14#issue-1960314205
