### ISSUE TITLE
Jellyfin+JavScraper，抓不了头像

### ISSUE THREAD

**Issue by Nemoljy** [gfriends/gfriends#95]
黑群晖6.23
Jellyfin 10.7.5
JavScraper v1.2021.622.2158
JavScraper的插件配置里配了代理（docker跑的v2ray）
Jav正常刮削影片信息和女友信息（文字介绍），但是在“计划任务”里多次运行采集头像也没法把头像下载下来。

运行时v2ray的日志：
![IMG_20220515_165832.jpg](https://user-images.githubusercontent.com/32947114/168465200-22285e60-c590-4f1c-a180-c6600dacfe4e.jpg)

Jellyfin的日志，感觉搜的人不太对劲：
![Screenshot_2022-05-15-17-01-47-526_com.z28j.feel.jpg](https://user-images.githubusercontent.com/32947114/168465217-2357de3d-7ad8-4137-b33c-d36fe1b1b9de.jpg)

**Comment by xinxin8816** [comment]
请去 [JavScraper issues](https://github.com/JavScraper/Emby.Plugins.JavScraper/issues) 反馈

**Comment by Nemoljy** [comment]
> 

好的，谢谢。
因为看到了这个issue里你的回答，https://github.com/xinxin8816/gfriends/issues/61#issuecomment-976671641
所以想请问下现在对Jellyfin的支持情况是怎么样呀？

**Comment by xinxin8816** [comment]
Gfriends Inputer 支援某些 Jellyfin 版本，未适配所有版本
